# Generated by Django 5.2.8 on 2025-11-15 16:43

import django.db.models.deletion
import joinCodes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=16, unique=True)),
                ('role', models.CharField(choices=[('WORKER', 'Trabajador')], default='WORKER', max_length=16)),
                ('max_uses', models.PositiveSmallIntegerField(default=1)),
                ('used_count', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField(default=joinCodes.models.default_code_expiry)),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_join_codes', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_codes', to='emprises.empresa')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JoinCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('join_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='joincodes.joincode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joincode_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
        migrations.AddIndex(
            model_name='joincode',
            index=models.Index(fields=['code'], name='joincodes_j_code_fe6dd5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='joincodeusage',
            unique_together={('join_code', 'user')},
        ),
    ]
