# Generated by Django 5.2.8 on 2025-11-30 02:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emprises', '0002_alter_empresa_owner'),
        ('zonecrop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('granularity', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('total_images', models.PositiveIntegerField(default=0)),
                ('total_detections', models.PositiveIntegerField(default=0)),
                ('avg_confidence', models.FloatField(blank=True, null=True)),
                ('top_labels', models.JSONField(default=list)),
                ('prevalence', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_reports', to='zonecrop.cultivo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_reports', to='emprises.empresa')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_reports', to='zonecrop.zona')),
            ],
        ),
        migrations.CreateModel(
            name='SessionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_count', models.PositiveIntegerField(default=0)),
                ('detections_count', models.PositiveIntegerField(default=0)),
                ('unique_labels', models.JSONField(default=list)),
                ('top_labels', models.JSONField(default=list)),
                ('average_confidence', models.FloatField(blank=True, null=True)),
                ('median_confidence', models.FloatField(blank=True, null=True)),
                ('lat_avg', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon_avg', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('low_confidence_flag', models.BooleanField(default=False)),
                ('suspicious_flag', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_reports', to='zonecrop.cultivo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_reports', to='emprises.empresa')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
