# Generated by Django 5.2.8 on 2025-11-30 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('scanners', '0001_initial'),
        ('zonecrop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionreport',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_report', to='scanners.scannersession'),
        ),
        migrations.AddField(
            model_name='sessionreport',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_reports', to='zonecrop.zona'),
        ),
        migrations.AddIndex(
            model_name='aggregatedreport',
            index=models.Index(fields=['empresa', 'date', 'granularity'], name='reports_agg_empresa_df8ccf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aggregatedreport',
            unique_together={('empresa', 'zona', 'cultivo', 'date', 'granularity')},
        ),
        migrations.AddIndex(
            model_name='sessionreport',
            index=models.Index(fields=['empresa', 'zona', 'cultivo'], name='reports_ses_empresa_51469e_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionreport',
            index=models.Index(fields=['generated_at'], name='reports_ses_generat_8abc36_idx'),
        ),
    ]
