# Generated by Django 5.2.9 on 2025-12-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionreport',
            name='suspicious_detections_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
