# Generated by Django 5.2.8 on 2025-11-15 16:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_id', models.CharField(db_index=True, max_length=12, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(max_length=160)),
                ('country', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Debe ser código ISO2 en mayúsculas')])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_emprises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'emprises_empresa',
                'indexes': [models.Index(fields=['tax_id'], name='emprises_em_tax_id_e7177f_idx'), models.Index(fields=['name'], name='emprises_em_name_084ff1_idx')],
            },
        ),
    ]
