# Generated by Django 5.2.8 on 2025-11-30 02:10

import django.db.models.deletion
import django.utils.timezone
import scanners.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emprises', '0002_alter_empresa_owner'),
        ('zonecrop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scans/%Y/%m/%d/', validators=[scanners.models.validate_image_format])),
                ('local_photo_path', models.CharField(blank=True, max_length=500, null=True)),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Scanner Image',
                'verbose_name_plural': 'Scanner Images',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('file_path', models.CharField(blank=True, max_length=512, null=True)),
                ('framework', models.CharField(default='tflite', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Model Version',
                'verbose_name_plural': 'Model Versions',
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ScannerSession',
            fields=[
                ('session_id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('worker_name', models.CharField(max_length=200)),
                ('model_version_string', models.CharField(default='1.0', max_length=50)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='ACTIVE', max_length=20)),
                ('total_scans', models.IntegerField(default=0)),
                ('healthy_count', models.IntegerField(default=0)),
                ('plague_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanner_sessions', to='zonecrop.cultivo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanner_sessions', to='emprises.empresa')),
                ('model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanners.modelversion')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanner_sessions', to=settings.AUTH_USER_MODEL)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanner_sessions', to='zonecrop.zona')),
            ],
            options={
                'verbose_name': 'Scanner Session',
                'verbose_name_plural': 'Scanner Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScannerResult',
            fields=[
                ('result_id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('photo_path', models.CharField(max_length=500)),
                ('classification', models.CharField(max_length=200)),
                ('confidence', models.FloatField()),
                ('has_plague', models.BooleanField(default=False)),
                ('report_id', models.IntegerField(blank=True, null=True)),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bbox', models.JSONField(blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scanners.scannerimage')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='scanners.scannersession')),
            ],
            options={
                'verbose_name': 'Scanner Result',
                'verbose_name_plural': 'Scanner Results',
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.AddField(
            model_name='scannerimage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='scanners.scannersession'),
        ),
        migrations.AddIndex(
            model_name='scannersession',
            index=models.Index(fields=['empresa', 'zona', 'cultivo'], name='scanners_sc_empresa_bc7153_idx'),
        ),
        migrations.AddIndex(
            model_name='scannersession',
            index=models.Index(fields=['owner', 'status'], name='scanners_sc_owner_i_51f76c_idx'),
        ),
        migrations.AddIndex(
            model_name='scannersession',
            index=models.Index(fields=['started_at'], name='scanners_sc_started_2c7eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='scannerresult',
            index=models.Index(fields=['session', 'has_plague'], name='scanners_sc_session_c49f76_idx'),
        ),
        migrations.AddIndex(
            model_name='scannerresult',
            index=models.Index(fields=['classification'], name='scanners_sc_classif_560247_idx'),
        ),
    ]
