# Generated by Django 5.2.7 on 2025-10-21 04:12

import cropcare_orgs.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('tax_id', models.CharField(blank=True, max_length=40)),
                ('country', models.CharField(default='CL', max_length=2)),
                ('timezone', models.CharField(default='America/Santiago', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('WORKER', 'Trabajador'), ('INDIVIDUAL', 'Individual')], default='INDIVIDUAL', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('can_manage_plots', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='cropcare_orgs.empresa')),
            ],
            options={
                'verbose_name': 'Perfil de Empleado',
                'verbose_name_plural': 'Perfiles de Empleado',
            },
        ),
        migrations.CreateModel(
            name='JoinCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('role', models.CharField(choices=[('WORKER', 'Trabajador')], default='WORKER', max_length=16)),
                ('max_uses', models.PositiveSmallIntegerField(default=1)),
                ('used_count', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, default=cropcare_orgs.models.default_code_expiry, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_join_codes', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_codes', to='cropcare_orgs.empresa')),
            ],
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['name'], name='cropcare_or_name_121d00_idx'),
        ),
        migrations.AddIndex(
            model_name='joincode',
            index=models.Index(fields=['code'], name='cropcare_or_code_e898e1_idx'),
        ),
    ]
