# Generated by Django 5.2.8 on 2025-11-15 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='emprises.empresa')),
            ],
            options={
                'db_table': 'zonecrop_zonas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerZoneAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_assignments', to=settings.AUTH_USER_MODEL)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_assignments', to='zonecrop.zona')),
            ],
            options={
                'verbose_name': 'Asignación trabajador-zona',
                'verbose_name_plural': 'Asignaciones trabajador-zona',
                'db_table': 'zonecrop_worker_zone_assignments',
            },
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to='zonecrop.zona')),
            ],
            options={
                'db_table': 'zonecrop_cultivos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='zona',
            index=models.Index(fields=['empresa', 'nombre'], name='zonecrop_zo_empresa_3ecfb3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='zona',
            unique_together={('nombre', 'empresa')},
        ),
        migrations.AddIndex(
            model_name='workerzoneassignment',
            index=models.Index(fields=['zona', 'worker'], name='zonecrop_wo_zona_id_fbac9f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workerzoneassignment',
            unique_together={('worker', 'zona')},
        ),
        migrations.AddIndex(
            model_name='cultivo',
            index=models.Index(fields=['zona', 'nombre'], name='zonecrop_cu_zona_id_3ddeac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cultivo',
            unique_together={('nombre', 'zona')},
        ),
    ]
