package com.capstone.cropcare.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

///CUSTOM NORMAL
val customBtn = Color(0xFF003D43)
val customGreen = Color(0xFF003D43)
val primaryLightMediumContrast = Color(0xFF003D43)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF177882)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF003E3A)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF1A7A73)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF003C45)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF197885)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF5FAFB)
val onBackgroundLightMediumContrast = Color(0xFF171D1E)
val surfaceLightMediumContrast = Color(0xFFF5FAFC)
val onSurfaceLightMediumContrast = Color(0xFF0C1214)
val surfaceVariantLightMediumContrast = Color(0xFFDBE4E7)
val onSurfaceVariantLightMediumContrast = Color(0xFF2F383A)
val outlineLightMediumContrast = Color(0xFF4B5457)
val outlineVariantLightMediumContrast = Color(0xFF666F71)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2B3133)
val inverseOnSurfaceLightMediumContrast = Color(0xFFECF2F4)
val inversePrimaryLightMediumContrast = Color(0xFF81D3DE)
val surfaceDimLightMediumContrast = Color(0xFFC2C7C9)
val surfaceBrightLightMediumContrast = Color(0xFFF5FAFC)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFEFF4F6)
val surfaceContainerLightMediumContrast = Color(0xFFE4E9EB)
val surfaceContainerHighLightMediumContrast = Color(0xFFD8DEE0)
val surfaceContainerHighestLightMediumContrast = Color(0xFFCDD2D4)



//CUSTOM DARK
val customBtnDark = Color(0xFF003D43)

val primaryDarkHighContrast = Color(0xFFCAF8FF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF7DCFDA)
val onPrimaryContainerDarkHighContrast = Color(0xFF000E10)
val secondaryDarkHighContrast = Color(0xFFACFFF6)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFF7DD1C9)
val onSecondaryContainerDarkHighContrast = Color(0xFF000E0C)
val tertiaryDarkHighContrast = Color(0xFFD0F7FF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFF7ECFDE)
val onTertiaryContainerDarkHighContrast = Color(0xFF000D11)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF0E1415)
val onBackgroundDarkHighContrast = Color(0xFFDEE4E4)
val surfaceDarkHighContrast = Color(0xFF0F1416)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF3F484B)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFE8F1F5)
val outlineVariantDarkHighContrast = Color(0xFFBBC4C7)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFDEE3E5)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF005058)
val surfaceDimDarkHighContrast = Color(0xFF0F1416)
val surfaceBrightDarkHighContrast = Color(0xFF4B5153)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1B2122)
val surfaceContainerDarkHighContrast = Color(0xFF2B3133)
val surfaceContainerHighDarkHighContrast = Color(0xFF363C3E)
val surfaceContainerHighestDarkHighContrast = Color(0xFF42484A)

//CUSTOMS
val BottomTextDisabled = Color(0xC1D9D9D9)
val placeholderColor = Color(0xC1D9D9D9).copy(alpha = 0.2f)

val checkColorIcon = Color(0xFF4CAF50)



